CREATE TABLE f1_results (
	resultId   	 				INT,
	gridQuali 		 			INT,
	positionText 		 		VARCHAR(MAX),
	positionOrder 		 		INT,
	points 		 				FLOAT,
	laps 		 				INT,
	milliseconds 		 		INT,
	fastestLap 		 			INT,
	fastestLapTime 		 		FLOAT,
	fastestLapSpeed 		 	FLOAT,
	statusId 		 			INT,
	status 		 				VARCHAR(MAX),
	raceId 		 				INT,
	season 		 				INT,
	raceRound 		 			INT,
	raceName 		 			VARCHAR(MAX),
	raceDate 		 			DATE,
	circuitId 		 			INT,
	circuitRef 		 			VARCHAR(MAX),
	circuitLocation 		 	VARCHAR(MAX),
	circuitCountry 		 		VARCHAR(MAX),
	driverId 		 			INT,
	driverRef 		 			VARCHAR(MAX),
	driverNumber 		 		INT,
	driverName 		 			VARCHAR(MAX),
	driverSurname 		 		VARCHAR(MAX),
	driverNationality 		 	VARCHAR(MAX),
	constructorId 		 		INT,
	constructorName 		 	VARCHAR(MAX),
	constructorNationality 		VARCHAR(MAX)
);
GO