name: mc_reco
channels:
- https://conda.anaconda.org
- https://repo.anaconda.com/pkgs
dependencies:
- lightfm=1.16
- pyarrow=4.0.1
- py4j=0.10.9.2
- boost-cpp=1.73.0
- aws-c-event-stream=0.1.6
- krb5=1.19.2
- libnghttp2=1.46.0
- libthrift=0.13.0
- abseil-cpp=20200225.2
- double-conversion=3.1.5
- c-ares=1.18.1
- gflags=2.2.2
- libevent=2.1.12
- uriparser=0.9.3
- snappy=1.1.9
- re2=2020.11.01
- orc=1.6.7
- libprotobuf=3.11.4
- utf8proc=2.6.1
- seaborn=0.11.2
- scipy=1.7.3
- wordcloud=1.8.1
- scikit-learn=1.0.2
- _libgcc_mutex=0.1
- matplotlib-base=3.5.1
- munkres=1.1.4
- qt=5.9.7
- fonttools=4.25.0
- gstreamer=1.14.0
- fontconfig=2.13.1
- brotli=1.0.9
- pcre=8.45
- cycler=0.11.0
- sip=4.19.8
- libxcb=1.14
- libtiff=4.2.0
- zstd=1.4.9
- freetype=2.11.0
- libpng=1.6.37
- libstdcxx-ng=9.3.0
- jupyterlab=3.3.2
- dbus=1.13.18
- pytz=2021.3
- pillow=9.0.1
- defusedxml=0.7.1
- babel=2.9.1
- idna=3.3
- pandocfilters=1.5.0
- testpath=0.5.0
- libuuid=1.0.3
- nbconvert=6.4.4
- pyzmq=22.3.0
- markupsafe=2.0.1
- joblib=1.1.0
- ca-certificates=2022.3.29
- glog=0.5.0
- typed-ast=1.4.3
- json5=0.9.6
- mypy_extensions=0.4.3
- _openmp_mutex=4.5
- libffi=3.3
- libgomp=11.2.0
- click=8.0.4
- libsodium=1.0.18
- lcms2=2.12
- libgfortran-ng=7.5.0
- pathspec=0.7.0
- bottleneck=1.3.4
- threadpoolctl=2.2.0
- libopenblas=0.3.18
- tk=8.6.11
- debugpy=1.5.1
- certifi=2021.10.8
- arrow-cpp=4.0.1
- matplotlib=3.5.1
- zipp=3.7.0
- pyparsing=3.0.4
- grpc-cpp=1.29.0
- backcall=0.2.0
- jupyter_core=4.9.2
- webencodings=0.5.1
- blas=1.0
- jupyter_highlight_selected_word=0.2.0
- importlib_metadata=4.11.3
- python-fastjsonschema=2.15.1
- soupsieve=2.3.1
- ld_impl_linux-64=2.35.1
- kiwisolver=1.3.2
- libgfortran4=7.5.0
- sqlite=3.38.2
- xz=5.2.5
- requests=2.27.1
- pip=21.2.2
- libcurl=7.82.0
- aws-c-common=0.4.57
- bleach=4.1.0
- matplotlib-inline=0.1.2
- zeromq=4.3.4
- decorator=5.1.1
- jedi=0.18.1
- argon2-cffi=21.3.0
- charset-normalizer=2.0.4
- pygments=2.11.2
- wheel=0.37.1
- setuptools=61.2.0
- appdirs=1.4.4
- expat=2.4.4
- numpy-base=1.21.5
- sniffio=1.2.0
- pyopenssl=22.0.0
- six=1.16.0
- openssl=1.1.1n
- python=3.7.13
- typing_extensions=4.1.1
- black=19.10b0
- pyspark=3.1.2
- toml=0.10.2
- pandas=1.3.5
- attrs=21.4.0
- traitlets=5.1.1
- ipykernel=6.9.1
- wcwidth=0.2.5
- send2trash=1.8.0
- bzip2=1.0.8
- glib=2.69.1
- prometheus_client=0.13.1
- jupyter_client=7.2.2
- notebook=6.4.8
- libwebp-base=1.2.2
- ipython_genutils=0.2.0
- jpeg=9e
- libwebp=1.2.2
- importlib_resources=5.2.0
- aws-checksums=0.1.9
- packaging=21.3
- numexpr=2.8.1
- jupyterlab_pygments=0.1.2
- libev=4.33
- typing-extensions=4.1.1
- cffi=1.15.0
- lz4-c=1.9.3
- readline=8.1.2
- pexpect=4.8.0
- libedit=3.1.20210910
- python-dateutil=2.8.2
- pyrsistent=0.18.0
- beautifulsoup4=4.11.1
- terminado=0.13.1
- jinja2=3.0.3
- lxml=4.8.0
- entrypoints=0.4
- nest-asyncio=1.5.5
- pickleshare=0.7.5
- jupyter_contrib_nbextensions=0.5.1
- libgcc-ng=11.2.0
- websocket-client=0.58.0
- importlib-metadata=4.11.3
- libboost=1.73.0
- mistune=0.8.4
- anyio=3.5.0
- aws-sdk-cpp=1.8.185
- cryptography=36.0.0
- zlib=1.2.12
- jupyter_contrib_core=0.3.3
- brotlipy=0.7.0
- jupyterlab_code_formatter=1.4.11
- ptyprocess=0.7.0
- argon2-cffi-bindings=21.2.0
- ipython=7.31.1
- jsonschema=4.4.0
- prompt-toolkit=3.0.20
- urllib3=1.26.9
- python_abi=3.7
- nbformat=5.3.0
- nbclient=0.5.13
- yaml=0.2.5
- jupyter_server=1.13.5
- libssh2=1.10.0
- pyqt=5.9.2
- ncurses=6.3
- nbclassic=0.3.5
- jupyterlab_server=2.12.0
- gst-plugins-base=1.14.0
- regex=2022.3.15
- jupyter_latex_envs=1.4.6
- icu=58.2
- parso=0.8.3
- pyyaml=6.0
- libxml2=2.9.12
- tornado=6.1
- numpy=1.21.5
- libxslt=1.1.34
- isort=5.9.3
- pycparser=2.21
- jupyter_nbextensions_configurator=0.4.1
- pysocks=1.7.1
- giflib=5.2.1

